
version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: 'mrbebo/yachtbookingapi:v1.0'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      url: jdbc:postgresql://postgres:5432/booking
      username: postgres
      password: admin

volumes:
  postgres-data:
