
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/booking
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

